spring:
  application:
    name: backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: acortador_db

app:
  jwt:
    secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
    expiration-ms: 86400000